language: ruby
rvm:
  - 2.0.0

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/redis.yml.sample config/redis.yml
  - psql -c 'create database zyg_test' -U postgres
  - rake db:migrate

script: 
  - rake spec

services:
  - redis-server


